### ISSUE TITLE
Error after patch 10 hours ago

### ISSUE THREAD

**Issue by jang9824** [hectorgimenez/koolo#212]
### Details

1. The stock is full when you gamble
I'm going to keep buying it without selling it

2. Even if you shut down the bot to clean up your inventory
Forced mouse movement

### Version

v0.4.0-beta5

**Comment by divineblade7** [comment]
Was doing the same to me in this latest commit 1303fc2. filling up inventory without selling gambled items. I just disabled gambling after it did it a couple games.  Log wasn’t helpful because it didn’t show any errors just that it was refreshing pages looking for coronets to gamble, when inventory is already full. Items did not match pickit.

**Comment by divineblade7** [comment]
> ### Version
> 
> v0.4.0-beta5

You sure you are on beta 5 @jang9824 ? that latest patch isnt the beta 5 release. that was a month and a half ago. beta 6 even was last week. did you build with that latest commit i mentioned or download a different release?

**Comment by jang9824** [comment]
> > ### 버전
> > v0.4.0-beta5
> 
> 베타 5를 사용하는 중이신가요?@jang9824? 최신 패치는 베타 5 릴리스가 아닙니다. 그게 한 달 반 전 메뉴입니다. 베타 6에도 불구하고. 내가 언급한 최신 커밋으로 만들거나 다른 릴리스를 다운로드했습니까?

1303FC2 Build and use the latest commit

**Comment by jang9824** [comment]
KEY is also stored in the inventory more than necessary

**Comment by hectorgimenez** [comment]
this should be fixed now
