### ISSUE TITLE
Bot has item stuck in hand

### ISSUE THREAD

**Issue by Unfolds** [hectorgimenez/koolo#38]
Bot has item stuck in hand and waves it around forever sometimes during runs

**Comment by hectorgimenez** [comment]
Are you using 0.2.0 release or building from source code?

**Comment by Unfolds** [comment]
2.0 version, I couldn't figure out how to do the build :P

**Comment by Unfolds** [comment]
Ok got the build one to work, no holding items in hands atleast but gets stuck when doing stash run, constantly hovers over items forever

**Comment by Unfolds** [comment]
No ideas?

**Comment by hectorgimenez** [comment]
mmm it might be related to high latency, it happens to me from time to time also when there is a lag spike or something. Do you think it's your case?

**Comment by Unfolds** [comment]
It's quite possible a lag spike, plenty of CPU and ram allocated, although i have noticed the longer it runs the clunkier it gets, what specific graphics settings do you use?



Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Unfolds** [comment]
Such as Sharpness, FXAA etc

**Comment by hectorgimenez** [comment]
I have everything at minimum quality and all the effects disabled. About turning off screenshots, I think is not possible right now but it could be something interesting to implement

**Comment by Unfolds** [comment]
Ok thats what I have been running on as well, Do you have a discord I can contact you on in regards to few issues?

**Comment by Millionaar** [comment]
I've experienced the same item in hand issue, and noticed that I was all out of ID scrolls.
The bot IDs the items in inventory straight after getting into a game or going through a TP. So could well be the issue. It clicked on the ID Tome, doesn't get a scroll because it's empty, but then clicks on the item anyway, picking it up instead of IDing it.

Has anyone else has seen the same? Sample size of 1 isn't great haha.

I haven't had the time to compile the code and test solutions yet, but hoping to have a play around in the new year. Pretty newbie coder though.

**Comment by hectorgimenez** [comment]
I think this should be fixed with latest releases, please try again.
