### ISSUE TITLE
Error fetching map data

### ISSUE THREAD

**Issue by iiBARDii** [hectorgimenez/koolo#472]
### Details

After character select the bot stop working with the following report 

I'm pretty sure that I have Diablo II: LoD 1.13c version installed and it is working. Any suggestions? 

### Version

0.5.1

### Logs

time=16:36:58 level=INFO msg="Waiting for character selection screen..."
time=16:37:19 level=INFO msg="Character selection screen found"
time=16:37:19 level=INFO msg="Selecting character..."
time=16:37:19 level=INFO msg="Character found"
time=16:37:23 level=DEBUG msg="Fetching map data..." seed=1171928281 difficulty=hell
time=16:37:23 level=ERROR msg="Error fetching map data: error fetching Map Data from Diablo II: LoD 1.13c game: exit status 1"

**Comment by iiBARDii** [comment]
yes all the paths to D2LOD and to D2R are absolutely correct. Doublechecked it

**Comment by Sunnyweeb** [comment]
does the d2 lod path lead to the folder where all the files are in it? like it should not lead to "..\d2 lod" and then in that folder is another diablo folder, it should lead to "..\d2 lod\diablo ii" (i hope u get what i mean)

and what run do you get this error? before this version u always got that map fetching error when using tz run (but thats fixed)

**Comment by bekaerre** [comment]
Hi, my bot are running correctly but today not... got these error:

time=12:50:31 level=INFO msg="Waiting for character selection screen..."
time=12:50:35 level=INFO msg=Stopping... configuration=VariosRuns
time=12:50:35 level=ERROR msg="error restoring memory" !BADKEY="Acceso denegado."
time=12:50:35 level=ERROR msg="error restoring memory" !BADKEY="Acceso denegado."
time=12:50:35 level=INFO msg="Failed to kill process" configuration=VariosRuns
time=12:50:35 level=INFO msg="Finished stopping" configuration=VariosRuns


help me to fix this issue. Many thanks!

**Comment by Sunnyweeb** [comment]
did you change anything? any run? it seems like its the same problem as OP, it can't get the map from d2 lod?

**Comment by Spexarn** [comment]
So i found the answer in the discord (its in the readme):

That error can mean one of 3 things:

Your classic diablo version is not 1.13c. Make sure to reinstall LOD 1.13c as it's required in order to obtain the game's map data. In case you're not sure where to download the correct version, there are links in the pinned message in the ⁠💬┃general  channel.

The koolo-map.exe is missing from the tools folder. In 99% of the cases, antiviruses like Windows Defender etc delete it as they believe it's suspicious. It's not. Make sure that you add an exception/exclusion for the entire Koolo folder or for that specific exe.

Sometimes you just have to restart your PC and the error will disappear.
...........................................................................................................................................................
I downloaded a d2-zip from https://mega.nz/file/FMggGCwa#0VZ3Lg7rqif78IQQS4i3DEqlgf1GIFHvnpM3T2BDwqk . extracted it and took that as my path, Works now.
