### ISSUE TITLE
Leveling issues

### ISSUE THREAD

**Issue by Supox-80** [hectorgimenez/koolo#63]
I've been playing around with the leveling part of the bot. I made a paladin and let the bot take him from Act 1 Normal to Hell Baal. I was actually surprised of how well it worked.

Major bugs:

1.	The max game time config causes the leveling to stop. 
	- Solution: Max game time should be ignored when leveling.

2. 	Act 2: Bot doesn't combine the staff parts after getting them. It cannot enter the Palace because of that.
	- Solution: Put the staff parts in to the cube and combine them. After that, talk to Drognan to let the bot enter the Palace.

3. 	Act 2: Bot doesn't talk to Jerhyn after killing Duriel. It can't get to act 3 because of that.

4. 	Act 3: Repairing equipment and buying more keys doesn't work because Hratli is still at the pier.
	- Solution: talk to Hratli when loading to Act 3, if he is standing at the pier.

5.	Act 5: When the bot thaws Anya it TP's back to town before the animation is finished. It cannot get the scroll because of that.
	- Solution: add a delay before TP'ing to town to let the animation finish.

6. 	Act 5: After killing the Ancients the bot doesn't wait long enough when opening the gate to Baal. It tries to go in and when it can't it logs out.
	- Solution: add a delay to let the gate open fully.

Minor bugs:

1. 	Act 5: Bot attacks towers instead of doors at Frigid Highlands, Arreat Plateau and Frozen Tundra. This makes getting trough these zones very difficult at some points without teleport.

2.	Act 2: Bot doesn't clear the room where the Horadic staff is inserted. This usually causes the bot to log out before getting to Duriel because it's health drops below chicken value. 

I would also add this to the Readme: You should level your character to level 6 so the bot can start using holy fire. Bot isn't good at melee attacks so it takes a long time for it to get there by itself. NOTE: Don't put any points to skills or attributes, instead let the bot do it itself.

**Comment by Millionaar** [comment]
Agreed I ran into most of these same issues also. But overall very impressed with how successful it was, so props!

Worth noting that I never had the Act 5 Anya and Ancients errors that you are talking about. But adding a delay can't hurt.

For Act 5 running and towers, I found this a major issue as bot couldn't get passed these sections because either:
  - Attacking towers instead of doors.
  - Trying to get to a specific co-ordinates that were on the other side (or inside) the walls, so it could never get there.
  These are potentially more problematic in Single Player, as the map never changes it runs into the same issue over and over. Online might be okay as eventually it'll get a map that works.

To add:
Act 3:
  - Sometimes the Act 3 map completely skips the Great Marsh, i.e. the map leads the Spider Forest directly into the Flayer Jungle. Pretty sure this meant the bot had no idea how to progress. Low sample size so I'm not 100% sure.

**Comment by Supox-80** [comment]
I forgot to mention that I did the leveling in online mode, so the delay problems might be caused because of that.

**Comment by hectorgimenez** [comment]
Wow awesome! When I coded the leveling stuff I was quite skeptical that anyone would try to use it, is pretty basic right now, and honestly probably there are better ways to do it (or better builds?). Let me go through all those points during the following days, implement some of your feedback points should be relatively easy I think.

Thanks!

**Comment by hectorgimenez** [comment]
> * Sometimes the Act 3 map completely skips the Great Marsh, i.e. the map leads the Spider Forest directly into the Flayer Jungle. Pretty sure this meant the bot had no idea how to progress. Low sample size so I'm not 100% sure.

Oh, just noticed about this part of the message! It's true that I had some troubles on that area but never noticed it was because this detail, mmm... Let me think about it, I believe it should not be very hard to fix.

**Comment by artosimonyan** [comment]
Leveling will be completely reworked in the upcoming versions and improved.
